### ISSUE TITLE
State of JS 2021

### ISSUE THREAD

**Issue by thiagoloal** [StateOfJS/locale-pt-BR#7]
Lista de seções que necessitam de traduções  para [State of JS 2021](https://2021.stateofjs.com/en-US/)

### Results
- [x] [**state_of_js_2021_results.yml**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_js_2021_results.yml)
  - [x] General
  - [x] Introduction
  - [x] Tshirt
  - [x] Sections
  - [x] Charts
  - [x] Notes
  - [x] Awards
  - [x] Conclusion
  - [x] Picks

### Survey
- [x] [**state_of_js_2021_survey**](https://github.com/StateOfJS/locale-pt-BR/blob/main/state_of_js_2021_survey.yml)
  - [x] General
  - [x] Survey

**Comment by willmustafa** [comment]
Olá, entrei no time para traduzir e estou revivendo aqui. Farei essas traduções, mas eu preciso criar alguma branch ou faço as mudanças diretas na master?

**Comment by willmustafa** [comment]
Done
